name: ci/gh-actions/build

on: [push, pull_request]

jobs:
  build-ubuntu-without-scanner:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: update apt
        run: sudo apt update
      - name: install dependencies
        run: sudo apt -y install git cmake build-essential ccache libssl-dev libunbound-dev libboost-all-dev
                                 libqrencode-dev qt6-base-dev qt6-svg-dev qt6-websockets-dev qt6-multimedia-dev
                                 qt6-wayland-dev libzip-dev libsodium-dev libgcrypt20-dev libx11-xcb-dev
                                 protobuf-compiler libprotobuf-dev libhidapi-dev libzxing-dev libusb-dev
                                 libusb-1.0-0-dev
      - name: build
        run: |
          mkdir build
          cd build
          cmake -DWITH_SCANNER=OFF ..
          cmake --build . -j $(nproc)
